### ISSUE TITLE
Mainframe Simulator API Design

### ISSUE THREAD

**Issue by mentlsve** [ckurze/mongodb-demo-insurance#1]
Does the following API structure make sense?

```
GET example.com/policies // returns all policies
GET example.com/policies?type=motor // returns only motor policies
GET example.com/policies?type=home // returns only home policies
GET example.com/customers // returns all customers
GET example.com/policies/PC_000001 // return details of policy PC_000001
POST example.com/policies // create new policy
GET example.com/policies/PC_000001/claims // returns all claims issued against a particular policy
POST example.com/policies/PC_000001 // create new claim against policy
```

We could skip the last two endpoints (working with claims) for the first iteration.

**Comment by schabiyo** [comment]
For this API: example.com/policies/PC_000001 // return details of policy PC_000001
Shouldn't we specify the type of policy as a query param? like

example.com/policies/PC_000001?type=motor

**Comment by schabiyo** [comment]
Done!
I'm using the structure below. The only change from our last discussion is that I got rid of the "claims" folder and instead use the policyID as the folder name for the claims. I'm also using a GUID for new created claim or Policy

├── customer
├── home
│   └── policies
│       ├── PC_000000001.json
│       └── PC_000000002.json
└── motor
    └── policies
        ├── PC_000000001
        │   ├── 36a2d34d-2980-45d8-a3e2-df4a17b7ba5e.json
        │   ├── 61dd0dfb-fce1-43dc-8f18-35baaf516669.json
        │   └── 8da65dba-79d0-46e2-ae61-72bb7434d3d1.json
        ├── PC_000000001.json
        ├── PC_000000002
        │   ├── 191541e2-b9d9-4621-9400-f5656fa4fa28.json
        │   ├── a5d02011-f309-4fde-8254-9eca0f4ffb53.json
        │   └── fac0c7b1-ad9e-4207-95ba-2da134b6269d.json
        └── PC_000000002.json

**Comment by schabiyo** [comment]
For the Create API, I'm saving everything received in the form directly to a file. I'm not using a Spring Bean to encapsulate the form data. This way the API will not have to change if we decide to add or modify a new attribute of  claim/policy.
