### ISSUE TITLE
Policy ID format

### ISSUE THREAD

**Issue by mentlsve** [ckurze/mongodb-demo-insurance#2]
The policy id generated by the mainframe simulator is a UUID (e.g. "0bdc549d-6bd3-485d-ba17-fee32e8417ce") in line 161 of [SimulatorController.java](https://github.com/ckurze/mongodb-demo-insurance/blob/master/mainframe_offloading/mainframe-simulator/src/main/java/com/mongodb/c4c/mainframe/simulator/SimulatorController.java)

The policy ids which can be found in the csv files have the form PC_<9 digits> (e.g. PC_000000001).

UUIDs might be easier to implement on the simulator side. For the format PC_<9 digits> we would need to keep track of the next unused number.

Should we stick to one common ID format? And if yes to which.

**Comment by schabiyo** [comment]
GUUID prevents keeping track of the last number.  But again if this make things easier as you are the consumer, I will add that logic in the back-end. Just let me know.

**Comment by schabiyo** [comment]
Hum let me change it on my side :) It indeed look better using the PC_*** convention

**Comment by schabiyo** [comment]
Done!
